plugins {
    id 'java'
}

group = 'com.flyaway.thunderrider'
version = '1.2.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven {
        name = "papermc"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven { url = "https://maven.enginehub.org/repo/" }
    maven { url = 'https://repo.essentialsx.net/releases/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.3.build.159-beta'
    compileOnly('com.sk89q.worldguard:worldguard-bukkit:7.0.18') {
        exclude group: 'com.google.guava', module: 'guava'
        exclude group: 'com.google.code.gson', module: 'gson'
    }
    compileOnly 'net.essentialsx:EssentialsX:2.21.2'
}

tasks.jar {
    archiveBaseName.set("ThunderRider")
}

tasks.processResources {
    filesMatching("plugin.yml") {
        expand(
                version: project.version,
                name: project.name,
                group: project.group
        )
    }
}
