name: ThunderRider
version: 1.1.1
main: com.flyaway.thunderrider.ThunderRider
api-version: 1.21
description: Spawns lightning and skeleton riders near players
author: FlyAwayMaking
website: https://github.com/flyawaymaking
softdepend:
  - Essentials
  - WorldGuard

commands:
  thunderider:
    description: Control the ThunderRider plugin
    usage: /<command> <reload|start|stop|spawn>
    permission: thunderrider.admin

permissions:
  thunderrider.admin:
    description: Admin permissions for ThunderRider
    default: op
  thunderrider.ignore:
    description: Ignore spawning ThunderRider
    default: op
